services:
  expo-app:
    container_name: login-app
    build:
      context: .
    ports:
      - "19000:19000" # Port pour le QR code (Expo Dev Tools)
      - "19001:19001" # Port pour les logs Metro
      - "19002:19002" # Port pour WebSocket
    volumes:
      - .:/app
    stdin_open: true
    tty: true
